//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class ProjectModule : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProjectModule defaultInstance = ((ProjectModule)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProjectModule())));
        
        public static ProjectModule Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProjectModule")]
        public string ProjectModulePath {
            get {
                return ((string)(this["ProjectModulePath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("  Demo.PrimaryInfo.Module.dll  ;  eon fe aa.dll ;dfaef.dll; asdfa asd.dll  ")]
        public string InfoModules {
            get {
                return ((string)(this["InfoModules"]));
            }
            set {
                this["InfoModules"] = value;
            }
        }
    }
}
